# Generated by Django 5.0.3 on 2024-03-27 01:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TabelBuku',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_buku', models.CharField(max_length=7)),
                ('kategori', models.CharField(max_length=20)),
                ('nama_buku', models.CharField(max_length=200)),
                ('penulis', models.CharField(max_length=200)),
                ('deskripsi', models.TextField()),
                ('halaman', models.IntegerField()),
                ('harga', models.IntegerField()),
                ('stok', models.IntegerField()),
                ('penerbit', models.CharField(max_length=200)),
                ('cover', models.ImageField(blank=True, null=True, upload_to='images')),
            ],
        ),
        migrations.CreateModel(
            name='TabelPenerbit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_penerbit', models.CharField(max_length=7)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='images')),
                ('nama', models.CharField(max_length=200)),
                ('alamat', models.TextField()),
                ('kota', models.CharField(max_length=100)),
                ('telepon', models.CharField(max_length=20)),
            ],
        ),
    ]
